<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=default,promise,fetch" defer></script>
<script src="assets/js/vendor/modernizr.min.js" defer></script>
<script src="assets/js/vendor/jquery.min.js" defer></script>
<script src="assets/js/vendor/object-fit-images.min.js" defer></script>
<script src="assets/js/vendor/jquery.nav.min.js" defer></script>
<script src="assets/js/vendor/slick.min.js" defer></script>
<script src="assets/js/vendor/sprintf.min.js" defer></script>
<script src="assets/js/vendor/jquery.lazyload.min.js" defer></script>
<script src="assets/js/vendor/jquery.colorbox.min.js" defer></script>
<script src="assets/js/main.min.js" defer></script>